const products = [
    {
        id: 1,
        name: "Eclipse Noir Black Table",
        imageUrl: "/Product_img/products1.png",
        rating: 4.5,
        price: 29.99,
        reviews: 245,
        type: "Table",
        brand: "VisiFurnish",
        material: "Wood",
        color: "Black",
        weight: "Light",
        stock: 10,
        shortDescription: "Elegant black wooden table for modern homes.",
        detailDescription: "The Eclipse Noir Table is crafted with premium wood and finished in sleek black, adding sophistication to any living space. Lightweight yet sturdy, it's perfect for both functional use and aesthetic appeal. Ideal for dining or living rooms."
       
    },
    {
        id: 2,
        name: "Rustic Harmony Coffee Table",
        imageUrl: "/Product_img/products2.png",
        rating: 4.2,
        price: 39.99,
        reviews: 130,
        type: "Table",
        brand: "VisiNest",
        material: "Wood",
        color: "Brown",
        weight: "Medium",
        stock: 8,
        shortDescription: "Stylish brown coffee table with a minimalist design.",
        detailDescription: "The Rustic Harmony Coffee Table features a minimalist wooden design, perfect for any contemporary living room. Its medium-weight build ensures durability while maintaining easy mobility. Ideal for serving beverages or as a stylish centerpiece."
    },
    {
        id: 3,
        name: "Majestic Leather Lounger",
        imageUrl: "/Product_img/products3.png",
        rating: 5.0,
        price: 49.99,
        reviews: 310,
        type: "Sofa",
        brand: "VisiARrange",
        material: "Leather",
        color:"Brown",
        weight: "Heavy",
        stock: 5,
        shortDescription: "Luxurious leather sofa with a timeless design.",
        detailDescription: "The Majestic Leather Lounger offers premium comfort with its high-quality leather upholstery. The elegant gray finish pairs well with modern and traditional interiors alike. Perfect for living rooms, offering a blend of style and comfort."

    },
    {
        id: 4,
        name: "Velvet Bliss Recliner Sofa",
        imageUrl: "/Product_img/products4.png",
        rating: 5.0,
        price: 49.99,
        reviews: 310,
        type: "Sofa",
        brand: "VisiFurnish",
        material: "Fabric",
        color: "Brown",
        weight: "Medium",
        stock: 7,
        shortDescription: "Comfortable fabric recliner sofa in a sleek black finish.",
        detailDescription: "Relax in style with the Velvet Bliss Recliner, designed for maximum comfort. The soft fabric and reclining feature make it perfect for unwinding after a long day. With its modern black finish, it easily complements any room decor."
    },
    {
        id: 5,
        name: "Cozy Nook Single Seat Sofa",
        imageUrl: "/Product_img/products5.png",
        rating: 4.0,
        price: 19.99,
        reviews: 120,
        type: "Sofa",
        brand: "VisiNest",
        material: "Wood",
        color: "Brown",
        weight: "Light",
        stock: 15,
        shortDescription: "Compact single-seat sofa made of wood.",
        detailDescription: "Perfect for small spaces, the Cozy Nook Single Seat offers comfort and durability in a compact design. The brown wooden frame provides a sturdy base, while the cushioned seat ensures comfort. Ideal for living rooms or cozy reading nooks."
    },
    {
        id: 6,
        name: "Vintage Grace Dressing Table",
        imageUrl: "/Product_img/products6.png",
        rating: 4.8,
        price: 69.99,
        reviews: 500,
        type: "Table",
        brand: "VisiARrange",
        material: "Wood",
        color: "Brown",
        weight: "Heavy",
        stock: 4,
        shortDescription: "Elegant antique-style wooden dressing table.",
        detailDescription: "The Vintage Grace Dressing Table brings a touch of vintage charm to your bedroom. Featuring a spacious tabletop and intricate wood detailing, it offers both functionality and timeless beauty. Ideal for organizing personal items and accessories."
    },
    {
        id: 7,
        name: "Timeless Vanity Station",
        imageUrl: "/Product_img/products7.png",
        rating: 3.9,
        price: 22.99,
        reviews: 85,
        type: "Table",
        brand: "VisiFurnish",
        material: "Wood",
        color: "Brown",
        weight: "Light",
        stock: 10,
        shortDescription: "Chic and functional vanity table for daily use.",
        detailDescription: "The Timeless Vanity Station is perfect for makeup and grooming routines. Its compact size fits well in smaller spaces, while the wooden design adds a warm, natural touch. Features ample storage space for beauty essentials."
    },
    {
        id: 8,
        name: "Shadow Stow Cupboard",
        imageUrl: "/Product_img/products8.png",
        rating: 4.3,
        price: 33.99,
        reviews: 205,
        type: "Storage",
        brand: "VisiNest",
        material: "Wood",
        color: "Brown",
        weight: "Medium",
        stock: 6,
        shortDescription: "Sturdy black wooden cupboard for extra storage.",
        detailDescription: "The Shadow Stow Cupboard provides ample storage space with a sturdy wooden build. Finished in sleek black, this medium-weight cupboard is ideal for bedrooms, living rooms, or offices, helping you stay organized while enhancing your decor."
    },
    {
        id: 9,
        name: "Abstract Horizon Canvas",
        imageUrl: "/Product_img/products9.png",
        rating: 4.7,
        price: 55.99,
        reviews: 315,
        type: "Decor",
        brand: "VisiARrange",
        material: "Canvas",
        color: "Silver",
        weight: "Light",
        stock: 20,
        shortDescription: "Contemporary abstract art on canvas for modern interiors.",
        detailDescription: "The Abstract Horizon Canvas piece is perfect for adding a modern and artistic touch to your living space. The subtle gray tones blend well with a variety of color schemes, making it a versatile decor item for any room in your home."
    },
    {
        id: 10,
        name: "Ivory Cloud White Sofa",
        imageUrl: "/Product_img/products10.png",
        rating: 5.0,
        price: 89.99,
        reviews: 400,
        type: "Sofa",
        brand: "VisiFurnish",
        material: "Fabric",
        color: "White",
        weight: "Heavy",
        stock: 3,
        shortDescription: "Spacious white fabric sofa for ultimate comfort.",
        detailDescription: "Sink into the plush cushions of the Ivory Cloud Sofa, designed with high-quality fabric and a sturdy frame. The neutral gray color makes it an easy fit for any home decor, while the heavy build ensures long-lasting durability."
    },
    {
        id: 11,
        name: "Sunshine Accent Brown Sofa",
        imageUrl: "/Product_img/products11.png",
        rating: 4.1,
        price: 23.99,
        reviews: 160,
        type: "Sofa",
        brand: "VisiNest",
        material: "Fabric",
        color: "Brown",
        weight: "Medium",
        stock: 8,
        shortDescription: "Stylish yellow accent sofa for a pop of color.",
        detailDescription: "Add a bold touch to your living room with the Sunshine Accent Sofa. Its medium-weight design makes it easy to move, while the vibrant color and soft fabric make it a comfortable and eye-catching addition to any space."
    },
    {
        id: 12,
        name: "Jetstream",
        imageUrl: "/Product_img/products13.jpg",
        rating: 4.6,
        price: 42.99,
        reviews: 280,
        type: "",
        brand: "VisiARrange",
        material: "Plastic",
        color: "Black",
        weight: "Light",
        stock: 12,
        shortDescription: "Sleek and durable plastic chair for modern interiors.",
        detailDescription: "The Jetstream Chair offers a minimalist and durable seating option for both indoor and outdoor spaces. Its black color and lightweight design make it versatile for any environment, providing comfort and style without compromising on durability."
    },
];  
export default products;